name: gantt_view
description: A Gantt Chart view for Flutter.
version: 0.0.2
homepage: https://pixelbeard.co/
repository: https://github.com/PixelBeardAgency/gantt-view
issue_tracker: https://github.com/PixelBeardAgency/gantt-view/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  benchmark_harness: any