name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  main:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Replace version number in flutter/pubspec.yaml
        run: |
          echo "RELEASE_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//'" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}"
          sed -i -r "s/version: [0-9]+\.[0-9]+\.[0-9]+/version: ${{ env.RELEASE_VERSION }}/g" pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: |
          flutter analyze
          flutter test

      - name: Publish to pub.dev
        run: flutter pub publish --force
